name: flutter_horizontal_date_picker
description: A Flutter package to create a Horizontal Date Picker. It will be useful for your awesome app.
version: 0.0.1
homepage: https://minhhung2556.github.io
repository: https://github.com/minhhung2556/romantic_project_flutter_horizontal_date_picker.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: